### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/farmit#8]
Add a CONTRIBUTING.md file. The same file should also be usable with https://github.com/techservicesillinois/awscli-login since farmit uses the same build system.

## Tasks

- [ ] document steps for PyEnv setup.
- [ ] document how the test suite.

**Comment by edthedev** [comment]
Maybe crib ideas from https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/blob/main/CONTRIBUTING.md
